### ISSUE TITLE
Compile issue on macOS (arm64)

### ISSUE THREAD

**Issue by twoplan** [jabolcni/Lambergar#6]
Hi,
just tried to compile version 1.3 on macOS 15 and got this error:

`zig build -Dtarget=aarch64-macos -Dcpu=apple_m1 -Doptimize=ReleaseFast`
```
build.zig:29:10: error: no field named 'root_source_file' in struct 'Build.ExecutableOptions'
        .root_source_file = b.path("src/main.zig"),
         ^~~~~~~~~~~~~~~~
/opt/homebrew/Cellar/zig/0.15.1/lib/zig/std/Build.zig:771:31: note: struct declared here
pub const ExecutableOptions = struct {
                              ^~~~~~
referenced by:
    runBuild__anon_21180: /opt/homebrew/Cellar/zig/0.15.1/lib/zig/std/Build.zig:2214:33
    main: /opt/homebrew/Cellar/zig/0.15.1/lib/zig/compiler/build_runner.zig:366:29
    4 reference(s) hidden; use '-freference-trace=6' to see all references
```

`zig version` is
```
0.15.1
```
And with  `zig build -freference-trace=6`                 
```
build.zig:29:10: error: no field named 'root_source_file' in struct 'Build.ExecutableOptions'
        .root_source_file = b.path("src/main.zig"),
         ^~~~~~~~~~~~~~~~
/opt/homebrew/Cellar/zig/0.15.1/lib/zig/std/Build.zig:771:31: note: struct declared here
pub const ExecutableOptions = struct {
                              ^~~~~~
referenced by:
    runBuild__anon_21180: /opt/homebrew/Cellar/zig/0.15.1/lib/zig/std/Build.zig:2214:33
    main: /opt/homebrew/Cellar/zig/0.15.1/lib/zig/compiler/build_runner.zig:366:29
    callMain [inlined]: /opt/homebrew/Cellar/zig/0.15.1/lib/zig/std/start.zig:627:37
    callMainWithArgs [inlined]: /opt/homebrew/Cellar/zig/0.15.1/lib/zig/std/start.zig:587:20
    main: /opt/homebrew/Cellar/zig/0.15.1/lib/zig/std/start.zig:602:28
    comptime: /opt/homebrew/Cellar/zig/0.15.1/lib/zig/std/start.zig:62:30
```

**Comment by jabolcni** [comment]
The version 1.3 still requires zig 0.14.1. I published dev branch of engine, which supports zig 0.15.1. Otherwise I can compile 1.3 for mac and publish it in releases

**Comment by twoplan** [comment]
The dev tree compiles fine with zig 0.15.1 here. 

**It would be great if you could provide mac binaries in your releases!**

**Comment by jabolcni** [comment]
Great, I will add mac binaries to releases from now on.
